ALTER TABLE characters ADD COLUMN total_xp INT NOT NULL DEFAULT 0;
ALTER TABLE characters ADD COLUMN dead BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE characters ADD COLUMN retainer BOOLEAN NOT NULL DEFAULT FALSE;