// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Sidebar(active string, username string, authorized bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!--\n<nav class=\"sidebar flex-shrink-0 p-3 border-end border-1 border-light\"\n    style=\"width: 280px; height: 100vh; background-color: #181818;\">\n    <div class=\"d-flex justify-content-center mb-4\">\n        <a href=\"/home\">\n            <img src=\"/static/img/logo-225x225.png\" class=\"mx-auto\" width=\"100%\" height=\"100%\" />\n        </a>\n    </div>\n    if authorized {\n    <ul class=\"nav nav-pills flex-column\">\n        <li class=\"nav-anchor-item\">\n            if active == \"Account\" {\n            <a class=\"nav-anchor-active\" href=\"/account\">{ username }</a>\n            } else {\n            <a class=\"nav-anchor\" href=\"/account\">{ username }</a>\n            }\n        </li>\n        <li class=\"nav-anchor-item\">\n            if active == \"Campaigns\" {\n            <a class=\"nav-anchor-active\" href=\"/campaigns\">Campaigns</a>\n            } else {\n            <a class=\"nav-anchor\" href=\"/campaigns\">Campaigns</a>\n            }\n        </li>\n        <li class=\"nav-anchor-item mt-4\">\n            <a class=\"nav-anchor\" href=\"/logout\">Logout</a>\n        </li>\n    </ul>\n    } else {\n            <ul class=\"nav nav-pills flex-column\">\n        <li class=\"nav-anchor-item\">\n            <a class=\"nav-anchor\" href=\"/login\">Login</a>\n        </li>\n</ul>\n    }\n</nav>\n-->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
