// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Campaign struct {
	ID             int64
	Name           string
	Description    sql.NullString
	Key            string
	UserID         int64
	CreateDatetime time.Time
}

type Character struct {
	ID             int64
	Name           string
	PlayerName     string
	XpBonus        int64
	CampaignID     int64
	CreateDatetime time.Time
}

type User struct {
	ID             int64
	Username       string
	Realname       sql.NullString
	Password       string
	CreateDatetime time.Time
}

type XpAward struct {
	ID               int64
	XpAward          int64
	XpAwardWithBonus int64
	Reason           string
	CharacterID      int64
	CreateDatetime   time.Time
}

type XpBonusReason struct {
	ID             int64
	XpBonus        int64
	Reason         string
	CharacterID    int64
	CreateDatetime time.Time
}
