// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Campaign struct {
	ID             int32
	Name           string
	Description    sql.NullString
	KeyField       string
	UserID         int32
	CreateDatetime time.Time
}

type Character struct {
	ID             int32
	Name           string
	PlayerName     string
	XpBonus        int32
	CampaignID     int32
	CreateDatetime time.Time
	TotalXp        int32
	Dead           bool
	Retainer       bool
}

type User struct {
	ID             int32
	Username       string
	Realname       sql.NullString
	Password       string
	CreateDatetime time.Time
}

type XpAward struct {
	ID               int32
	XpAward          int32
	XpAwardWithBonus int32
	Reason           string
	CharacterID      int32
	CreateDatetime   time.Time
}

type XpBonusReason struct {
	ID             int32
	XpBonus        int32
	Reason         string
	CharacterID    int32
	CreateDatetime time.Time
}
