// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const getLatestUserByID = `-- name: GetLatestUserByID :one
SELECT id, username, realname, password, create_datetime FROM users WHERE id = LAST_INSERT_ID()
`

func (q *Queries) GetLatestUserByID(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getLatestUserByID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Realname,
		&i.Password,
		&i.CreateDatetime,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, realname, password, create_datetime FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Realname,
		&i.Password,
		&i.CreateDatetime,
	)
	return i, err
}

const getUserId = `-- name: GetUserId :one
SELECT id
FROM users
WHERE username = ? 
LIMIT 1
`

func (q *Queries) GetUserId(ctx context.Context, username string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserId, username)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, realname, password, create_datetime FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Realname,
			&i.Password,
			&i.CreateDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (username, realname, password, create_datetime)
VALUES (?, ?, ?, now())
`

type InsertUserParams struct {
	Username string
	Realname sql.NullString
	Password string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.Username, arg.Realname, arg.Password)
	return err
}
