// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: xpbonusreasons.sql

package db

import (
	"context"
)

const deleteXpBonusForCharacter = `-- name: DeleteXpBonusForCharacter :exec
DELETE FROM xp_bonus_reasons
WHERE character_id = ?
`

func (q *Queries) DeleteXpBonusForCharacter(ctx context.Context, characterID int64) error {
	_, err := q.db.ExecContext(ctx, deleteXpBonusForCharacter, characterID)
	return err
}

const getXpBonusForCharacter = `-- name: GetXpBonusForCharacter :many
SELECT id, xp_bonus, reason, character_id, create_datetime FROM xp_bonus_reasons
WHERE character_id = ?
`

func (q *Queries) GetXpBonusForCharacter(ctx context.Context, characterID int64) ([]XpBonusReason, error) {
	rows, err := q.db.QueryContext(ctx, getXpBonusForCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XpBonusReason
	for rows.Next() {
		var i XpBonusReason
		if err := rows.Scan(
			&i.ID,
			&i.XpBonus,
			&i.Reason,
			&i.CharacterID,
			&i.CreateDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertXpBonusForCharacter = `-- name: InsertXpBonusForCharacter :one
INSERT INTO xp_bonus_reasons (xp_bonus, reason, character_id, create_datetime)
VALUES (?, ?, ?, now())
RETURNING id, xp_bonus, reason, character_id, create_datetime
`

type InsertXpBonusForCharacterParams struct {
	XpBonus     int64
	Reason      string
	CharacterID int64
}

func (q *Queries) InsertXpBonusForCharacter(ctx context.Context, arg InsertXpBonusForCharacterParams) (XpBonusReason, error) {
	row := q.db.QueryRowContext(ctx, insertXpBonusForCharacter, arg.XpBonus, arg.Reason, arg.CharacterID)
	var i XpBonusReason
	err := row.Scan(
		&i.ID,
		&i.XpBonus,
		&i.Reason,
		&i.CharacterID,
		&i.CreateDatetime,
	)
	return i, err
}
